In [1]:
import tensorflow as tf

2024-11-20 19:05:57.575350: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
X = tf.range(10, dtype=tf.float32)

In [6]:
dataset = tf.data.Dataset.from_tensor_slices(X)

In [8]:
for item in dataset:
    print(item)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(9.0, shape=(), dtype=float32)


2024-11-20 19:17:06.365106: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [9]:
X_nested = {
    'a': ([1, 2, 3], [4, 5, 6]),
    'b': [7, 8, 9]
}

In [11]:
dataset = tf.data.Dataset.from_tensor_slices(X_nested)

In [14]:
for item in dataset:
    print(item)

{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=5>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=6>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>}


2024-11-20 19:23:25.292800: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [1]:
import tensorflow as tf

2024-11-11 19:14:25.097968: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
X = tf.range(600)

# Chaining Transformation

In [10]:
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset = dataset.batch(32)
dataset = dataset.repeat(10)

In [11]:
for item in dataset:
    print(item)

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31], shape=(32,), dtype=int32)
tf.Tensor(
[32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55
 56 57 58 59 60 61 62 63], shape=(32,), dtype=int32)
tf.Tensor(
[64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87
 88 89 90 91 92 93 94 95], shape=(32,), dtype=int32)
tf.Tensor(
[ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
 114 115 116 117 118 119 120 121 122 123 124 125 126 127], shape=(32,), dtype=int32)
tf.Tensor(
[128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159], shape=(32,), dtype=int32)
tf.Tensor(
[160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
 178 179 180 181 182 183 184 185 186 187 188 189 190 191], shape=(32,), dtype=int32)
tf.Tensor(
[192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 20

2024-11-11 19:15:49.328332: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


# Batch of Tensors

In [18]:
X = tf.range(25)
X

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [19]:
dataset = tf.data.Dataset.from_tensor_slices(X)

In [20]:
dataset = dataset.map(lambda x: x ** 2)
dataset

<_MapDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [22]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(49, shape=(), dtype=int32)
tf.Tensor(64, shape=(), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)
tf.Tensor(100, shape=(), dtype=int32)
tf.Tensor(121, shape=(), dtype=int32)
tf.Tensor(144, shape=(), dtype=int32)
tf.Tensor(169, shape=(), dtype=int32)
tf.Tensor(196, shape=(), dtype=int32)
tf.Tensor(225, shape=(), dtype=int32)
tf.Tensor(256, shape=(), dtype=int32)
tf.Tensor(289, shape=(), dtype=int32)
tf.Tensor(324, shape=(), dtype=int32)
tf.Tensor(361, shape=(), dtype=int32)
tf.Tensor(400, shape=(), dtype=int32)
tf.Tensor(441, shape=(), dtype=int32)
tf.Tensor(484, shape=(), dtype=int32)
tf.Tensor(529, shape=(), dtype=int32)
tf.Tensor(576, shape=(), dtype=int32)


2024-11-11 19:18:09.010162: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


# Shuffling the data

In [23]:
dataset = tf.data.Dataset.range(100).repeat(3)
dataset

<_RepeatDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>

In [24]:
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(7)

In [26]:
for item in dataset:
    print(item)

tf.Tensor([3 5 2 1 8 4 0], shape=(7,), dtype=int64)
tf.Tensor([11 12 13  7  9 15 10], shape=(7,), dtype=int64)
tf.Tensor([17 14 20 19 16 18 21], shape=(7,), dtype=int64)
tf.Tensor([22  6 26 24 29 30 31], shape=(7,), dtype=int64)
tf.Tensor([23 27 28 35 34 32 33], shape=(7,), dtype=int64)
tf.Tensor([25 38 40 37 41 44 45], shape=(7,), dtype=int64)
tf.Tensor([42 43 39 36 49 48 51], shape=(7,), dtype=int64)
tf.Tensor([46 50 47 52 55 56 58], shape=(7,), dtype=int64)
tf.Tensor([54 60 59 57 64 65 62], shape=(7,), dtype=int64)
tf.Tensor([66 67 61 68 63 72 70], shape=(7,), dtype=int64)
tf.Tensor([71 74 73 69 53 78 76], shape=(7,), dtype=int64)
tf.Tensor([80 77 83 84 75 81 82], shape=(7,), dtype=int64)
tf.Tensor([86 87 88 89 91 93 92], shape=(7,), dtype=int64)
tf.Tensor([79 96 97 95 85 94 98], shape=(7,), dtype=int64)
tf.Tensor([ 1  3  0  4 99  7  6], shape=(7,), dtype=int64)
tf.Tensor([ 5 90  2  9 10 11 15], shape=(7,), dtype=int64)
tf.Tensor([13  8 17 18 16 12 22], shape=(7,), dtype=int64)
tf.T

2024-11-11 19:21:09.166077: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
