In [8]:
import tensorflow as tf

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

In [6]:
housing = fetch_california_housing()

In [7]:
X, y = housing.data, housing.target

In [9]:
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.15)

In [10]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, test_size=0.15)

# Normalization Layer

In [15]:
norm_layer = tf.keras.layers.Normalization()

In [16]:
model = tf.keras.Sequential([
    norm_layer,
    tf.keras.layers.Dense(1)
])

In [17]:
model.compile(loss = 'mse', optimizer = 'adam')

In [18]:
norm_layer.adapt(X_train)

In [19]:
model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=4)

Epoch 1/4
466/466 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0463 - val_loss: 4.7949
Epoch 2/4
466/466 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4.3112 - val_loss: 2.8976
Epoch 3/4
466/466 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 2.6425 - val_loss: 1.7562
Epoch 4/4
466/466 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.5569 - val_loss: 1.1229


# Discretization Layer

In [20]:
age = tf.constant([[10], [93], [54], [67], [34], [16],[29], [55], [64]])

In [21]:
age

<tf.Tensor: shape=(9, 1), dtype=int32, numpy=
array([[10],
       [93],
       [54],
       [67],
       [34],
       [16],
       [29],
       [55],
       [64]], dtype=int32)>

In [22]:
discretization_layer = tf.keras.layers.Discretization(bin_boundaries=[18, 50])

In [23]:
age_categories = discretization_layer(age)

In [24]:
age_categories

<tf.Tensor: shape=(9, 1), dtype=int64, numpy=
array([[0],
       [2],
       [2],
       [2],
       [1],
       [0],
       [1],
       [2],
       [2]])>

# Category Encoding

In [25]:
onehot_layer = tf.keras.layers.CategoryEncoding(num_tokens=3)

In [26]:
onehot_layer(age_categories)

<tf.Tensor: shape=(9, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)>

# StringLookup Layer

In [74]:
cities = ['Dallas', 'Austin', 'Dallas', 'Austin', 'Fort-worth', 'Houston', 'Houston']

In [75]:
str_lookup_layer = tf.keras.layers.StringLookup()

In [76]:
str_lookup_layer.adapt(cities)

In [79]:
str_lookup_layer([['Austin'], ['Dallas']])

<tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[3],
       [2]])>