# The tf.data API

In [60]:
import tensorflow as tf

In [64]:
X = tf.range(5)

In [65]:
dataset = tf.data.Dataset.from_tensor_slices(X)

In [66]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


2024-12-24 05:18:54.755156: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


# Two dimensional Arrays

In [77]:
X_nested = {
    'a': ([1, 2, 3], [4, 5, 6]),
    'b':[7, 8, 9]
}

In [78]:
dataset = tf.data.Dataset.from_tensor_slices(X_nested)

In [79]:
for item in dataset:
    print(item)

{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=5>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=6>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>}


2024-12-24 05:22:04.130188: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


# tf.data.Dataset from various structures

In [92]:
X_nested = {
    'a': [[1, 2, 3], [4, 5, 6]],
    'b': [4, 5]
}
dataset = tf.data.Dataset.from_tensor_slices(X_nested)
for item in dataset:
    print(item)

{'a': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=4>}
{'a': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=5>}


2024-12-24 05:24:08.747622: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


# Chaining Transformations

In [93]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.repeat(7).batch(4, drop_remainder=True)

In [94]:
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([8 9 0 1], shape=(4,), dtype=int64)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([8 9 0 1], shape=(4,), dtype=int64)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([8 9 0 1], shape=(4,), dtype=int64)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)


2024-12-24 05:25:18.390791: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


## Example 2

In [95]:
dataset = tf.data.Dataset.from_tensor_slices(tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9]))
dataset = dataset.repeat(5).batch(5, drop_remainder=True)

In [97]:
for element in dataset:
    print(element)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([6 7 8 9 1], shape=(5,), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([7 8 9 1 2], shape=(5,), dtype=int32)
tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)
tf.Tensor([8 9 1 2 3], shape=(5,), dtype=int32)
tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int32)
tf.Tensor([9 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32)


2024-12-24 05:26:33.493076: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


## Applying map function and transforming each item

In [98]:
dataset = dataset.map(lambda x: x ** 2)
for item in dataset:
    print(item)

tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)
tf.Tensor([36 49 64 81  1], shape=(5,), dtype=int32)
tf.Tensor([ 4  9 16 25 36], shape=(5,), dtype=int32)
tf.Tensor([49 64 81  1  4], shape=(5,), dtype=int32)
tf.Tensor([ 9 16 25 36 49], shape=(5,), dtype=int32)
tf.Tensor([64 81  1  4  9], shape=(5,), dtype=int32)
tf.Tensor([16 25 36 49 64], shape=(5,), dtype=int32)
tf.Tensor([81  1  4  9 16], shape=(5,), dtype=int32)
tf.Tensor([25 36 49 64 81], shape=(5,), dtype=int32)


2024-12-24 05:27:30.882772: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


## Example 2

In [102]:
dataset = dataset.map(lambda x: tf.sqrt(tf.cast(x, tf.float32)))
for item in dataset:
    print(item)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([6. 7. 8. 9. 1.], shape=(5,), dtype=float32)
tf.Tensor([2. 3. 4. 5. 6.], shape=(5,), dtype=float32)
tf.Tensor([7. 8. 9. 1. 2.], shape=(5,), dtype=float32)
tf.Tensor([3. 4. 5. 6. 7.], shape=(5,), dtype=float32)
tf.Tensor([8. 9. 1. 2. 3.], shape=(5,), dtype=float32)
tf.Tensor([4. 5. 6. 7. 8.], shape=(5,), dtype=float32)
tf.Tensor([9. 1. 2. 3. 4.], shape=(5,), dtype=float32)
tf.Tensor([5. 6. 7. 8. 9.], shape=(5,), dtype=float32)


2024-12-24 05:29:52.350496: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


## Filtering the data

In [103]:
dataset = dataset.filter(lambda x: tf.reduce_sum(x)> 20)
for item in dataset:
    print(item)

tf.Tensor([6. 7. 8. 9. 1.], shape=(5,), dtype=float32)
tf.Tensor([7. 8. 9. 1. 2.], shape=(5,), dtype=float32)
tf.Tensor([3. 4. 5. 6. 7.], shape=(5,), dtype=float32)
tf.Tensor([8. 9. 1. 2. 3.], shape=(5,), dtype=float32)
tf.Tensor([4. 5. 6. 7. 8.], shape=(5,), dtype=float32)
tf.Tensor([5. 6. 7. 8. 9.], shape=(5,), dtype=float32)


2024-12-24 05:30:54.101592: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


# Shuffling the data

In [104]:
X = tf.range(100)

In [108]:
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset = dataset.shuffle(buffer_size=7, seed = 42).batch(7, drop_remainder=True)
for item in dataset:
    print(item)

tf.Tensor([ 5  4  0  1  2 11 10], shape=(7,), dtype=int32)
tf.Tensor([ 7  3 14 12 15  8  6], shape=(7,), dtype=int32)
tf.Tensor([17 18 13  9 20 22 26], shape=(7,), dtype=int32)
tf.Tensor([16 23 27 25 24 21 31], shape=(7,), dtype=int32)
tf.Tensor([33 28 34 19 38 37 36], shape=(7,), dtype=int32)
tf.Tensor([32 42 43 39 45 30 46], shape=(7,), dtype=int32)
tf.Tensor([40 49 35 50 51 53 44], shape=(7,), dtype=int32)
tf.Tensor([52 47 54 48 56 29 61], shape=(7,), dtype=int32)
tf.Tensor([58 55 64 59 60 66 65], shape=(7,), dtype=int32)
tf.Tensor([62 70 63 71 57 67 74], shape=(7,), dtype=int32)
tf.Tensor([75 76 78 79 72 68 82], shape=(7,), dtype=int32)
tf.Tensor([41 69 85 86 83 77 88], shape=(7,), dtype=int32)
tf.Tensor([73 87 80 92 84 81 91], shape=(7,), dtype=int32)
tf.Tensor([95 89 90 94 99 93 96], shape=(7,), dtype=int32)


2024-12-24 05:33:03.142666: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
